// ACTIONS COTIZACIONES LIST
export const COTIZACIONES_LIST_LOADING = "COTIZACIONES_LIST_LOADING";
export const COTIZACIONES_LIST_ERROR = "COTIZACIONES_LIST_ERRROR";
export const COTIZACIONES_LIST_SUCCESS = "COTIZACIONES_LIST_SUCCESS";
export const SET_SEARCH_COTIZACION = "SET_SEARCH_COTIZACION";
// ACTIONS COTIZACIONES DETAILS
export const COTIZACIONES_DETAILS_LOADING = "COTIZACIONES_DETAILS_LOADING";
export const COTIZACIONES_DETAILS_ERROR = "COTIZACIONES_DETAILS_LOADING";
export const COTIZACIONES_DETAILS_SUCCESS = "COTIZACIONES_DETAILS_SUCCESS";
